name: Upload from publish folder Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: publish
          account_name: devsolutionrepos
          container_name: private-solution-collection
          sas_token: ${{ secrets.SASTOKEN_MYDEV }}
          sync: true
